const CFG = { HOOK_SECONDS: 60, MIX_SECONDS: 4, HOOK_RATIO: 0.30, MAX_VOLUME: 100 };
const state = {
  queue: JSON.parse(localStorage.getItem('aura_queue') || '[]'),
  history: JSON.parse(localStorage.getItem('aura_history') || '[]'),
  currentIndex: -1, current: null, next: null, nextIndex: -1,
  mixOn: JSON.parse(localStorage.getItem('aura_mix') ?? 'true'),
  autoMusic: JSON.parse(localStorage.getItem('aura_auto_music') ?? 'true'),
  autoEQ: JSON.parse(localStorage.getItem('aura_auto_eq') ?? 'true'),
  selectedSearch: null, selectedQueue: 0, paused: false, startedAt: 0, duration: 0,
  playerA: null, playerB: null, active: 'A', mixTimer: null, progressTimer: null,
  playersReady: 0, apiReady: false, loaded: { A:false, B:false }
};

const $ = id => document.getElementById(id);
const els = { searchInput:$('searchInput'), searchMode:$('searchMode'), searchBtn:$('searchBtn'), searchList:$('searchList'), queueList:$('queueList'), addBtn:$('addBtn'), removeBtn:$('removeBtn'), clearBtn:$('clearBtn'), startBtn:$('startBtn'), pauseBtn:$('pauseBtn'), nextBtn:$('nextBtn'), prevBtn:$('prevBtn'), stopBtn:$('stopBtn'), mixBtn:$('mixBtn'), autoMusic:$('autoMusic'), autoEQ:$('autoEQ'), status:$('status'), engineClock:$('engineClock'), nextLabel:$('nextLabel'), modeLabel:$('modeLabel'), nowTitle:$('nowTitle'), meta:$('meta'), cover:$('cover'), coverFallback:$('coverFallback'), progress:$('progress'), timeline:$('timeline'), waveform:$('waveform'), clock:$('clock'), shuffle90Btn:$('shuffle90Btn'), artistBtn:$('artistBtn'), historyBtn:$('historyBtn'), historyModal:$('historyModal'), historyList:$('historyList'), closeHistory:$('closeHistory'), clearHistory:$('clearHistory'), toast:$('toast') };

function save(){ localStorage.setItem('aura_queue', JSON.stringify(state.queue)); localStorage.setItem('aura_history', JSON.stringify(state.history)); localStorage.setItem('aura_mix', JSON.stringify(state.mixOn)); localStorage.setItem('aura_auto_music', JSON.stringify(state.autoMusic)); localStorage.setItem('aura_auto_eq', JSON.stringify(state.autoEQ)); }
function fmt(s){ s=Math.max(0,Math.floor(Number(s)||0)); return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`; }
function toast(t){ els.toast.textContent=t; els.toast.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>els.toast.classList.remove('show'),2300); }
function uniqueQueue(){ const seen=new Set(); state.queue=state.queue.filter(x=>x?.id && !seen.has(x.id) && seen.add(x.id)); }
function currentPlayer(){ return state.active==='A'?state.playerA:state.playerB; }
function standbyPlayer(){ return state.active==='A'?state.playerB:state.playerA; }
function hookStart(duration){ return duration<=CFG.HOOK_SECONDS ? 0 : Math.min(duration*CFG.HOOK_RATIO, duration-CFG.HOOK_SECONDS); }

window.onYouTubeIframeAPIReady = function(){ state.apiReady=true; makePlayer('A','playerA'); makePlayer('B','playerB'); };
function makePlayer(which, id){ const player = new YT.Player(id,{width:'1',height:'1',videoId:'',playerVars:{autoplay:0,controls:0,disablekb:1,playsinline:1,rel:0,modestbranding:1},events:{onReady:()=>{ state.playersReady++; if(which==='A') state.playerA=player; else state.playerB=player; },onStateChange:e=>onYTState(which,e),onError:e=>setStatus('⚠️ YouTube เล่นเพลงนี้ไม่ได้ ('+e.data+')','bad')}}); }

function onYTState(which,e){ if(e.data===YT.PlayerState.ENDED){ if(which===state.active) transitionOrAdvance(); } }
function setStatus(text, cls='ok'){ els.status.textContent=text; els.status.className='status '+cls; }
function updateClock(){ const d=new Date(); els.clock.textContent=d.toLocaleTimeString('th-TH',{hour12:false})+' • '+d.toLocaleDateString('th-TH'); }
setInterval(updateClock,1000); updateClock();

async function search(q=els.searchInput.value.trim(), mode=els.searchMode.value, max=10){
  if(!q) return toast('พิมพ์ชื่อเพลงหรือศิลปินก่อน');
  els.searchList.innerHTML='<div class="track"><div></div><div>กำลังค้นหา…</div></div>'; state.selectedSearch=null;
  const exclude=[...new Set(state.queue.map(x=>x.id).filter(Boolean))].join(',');
  try{
    const r=await fetch(`/.netlify/functions/youtube-search?q=${encodeURIComponent(q)}&mode=${encodeURIComponent(mode)}&max=${max}&exclude=${encodeURIComponent(exclude)}`);
    const data=await r.json(); if(!r.ok) throw new Error(data.error||'Search failed');
    renderSearch(data);
  }catch(e){ els.searchList.innerHTML=''; setStatus('❌ '+e.message,'bad'); toast('ค้นหาไม่สำเร็จ — ตรวจ YOUTUBE_API_KEY'); }
}
function renderSearch(rows){ els.searchList.innerHTML=''; if(!rows.length){ els.searchList.innerHTML='<div class="track"><div></div><div>ไม่พบเพลง</div></div>'; return; } rows.forEach(track=>{ const el=document.createElement('div'); el.className='track'; el.innerHTML=`<img class="thumb" src="${escapeAttr(track.thumbnail)}" alt=""><div><div class="track-title">${escapeHtml(track.title)}</div><div class="track-sub">${escapeHtml(track.uploader)}</div></div>`; el.onclick=()=>{document.querySelectorAll('#searchList .track').forEach(x=>x.classList.remove('selected')); el.classList.add('selected'); state.selectedSearch=track;}; el.ondblclick=()=>{addTrack(track,true)}; els.searchList.appendChild(el); }); }
function escapeHtml(s){ return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function escapeAttr(s){return String(s).replace(/"/g,'&quot;');}

function addTrack(track,start=false){ if(!track?.id) return toast('เลือกเพลงก่อน'); state.queue.push({...track}); uniqueQueue(); state.selectedQueue=state.queue.length-1; save(); renderQueue(); if(start) startTrack(state.selectedQueue); else { toast('✅ เพิ่มเข้าคิวแล้ว'); if(state.current) prepareNext(); } }
function renderQueue(){ els.queueList.innerHTML=''; state.queue.forEach((t,i)=>{ const el=document.createElement('div'); el.className='queue-item '+(i===state.currentIndex?'current':''); el.draggable=true; el.dataset.index=i; el.innerHTML=`<div class="qnum">${i===state.currentIndex?'▶':i+1}</div><div><div class="track-title">${escapeHtml(t.title)}</div><div class="track-sub">${escapeHtml(t.uploader||'Unknown')}</div></div><div>⋮</div>`; el.onclick=()=>{state.selectedQueue=i; document.querySelectorAll('#queueList .queue-item').forEach(x=>x.classList.remove('selected')); el.classList.add('selected')}; el.ondblclick=()=>startTrack(i); el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',i)); el.addEventListener('dragover',e=>e.preventDefault()); el.addEventListener('drop',e=>{e.preventDefault(); const from=Number(e.dataTransfer.getData('text/plain')); const to=i; if(Number.isInteger(from)&&from!==to){const [m]=state.queue.splice(from,1);state.queue.splice(to,0,m); if(state.currentIndex===from)state.currentIndex=to; save();renderQueue();prepareNext();}}); els.queueList.appendChild(el); }); }
function addSelected(){ if(!state.selectedSearch) return toast('กรุณาเลือกเพลงจากผลการค้นหา'); addTrack(state.selectedSearch); }
function removeSelected(){ const i=state.selectedQueue; if(i<0||i>=state.queue.length) return; const isCurrent=i===state.currentIndex; state.queue.splice(i,1); if(i<state.currentIndex) state.currentIndex--; if(isCurrent) state.currentIndex=-1; save(); renderQueue(); if(state.current) prepareNext(); }
function clearQueue(){ state.queue=[]; state.selectedQueue=0; save(); renderQueue(); setStatus('ล้างคิวแล้ว • เพลงปัจจุบันยังเล่นอยู่'); }

function configurePlayer(p, track, volume=0, auto=false){ if(!p||!track?.id) return false; p.setVolume(volume); p.cueVideoById({videoId:track.id,startSeconds:state.mixOn?hookStart(Number(track.duration)||180):0}); return true; }
async function startTrack(i){ if(i<0||i>=state.queue.length) return toast('ยังไม่มีเพลงในคิว'); const track=state.queue[i]; state.currentIndex=i; state.current={...track}; state.selectedQueue=i; state.paused=false; clearMixTimer(); state.active='A'; state.loaded={A:false,B:false}; state.playerA?.stopVideo(); state.playerB?.stopVideo(); renderQueue(); updateNow(); setStatus('กำลังเตรียมเพลง…'); els.engineClock.textContent='AUTO MIX • LOADING';
  const p=currentPlayer(); if(!p) return toast('กำลังโหลด YouTube Player…'); p.loadVideoById({videoId:track.id,startSeconds:state.mixOn?hookStart(Number(track.duration)||180):0}); p.setVolume(CFG.MAX_VOLUME); p.playVideo(); state.startedAt=performance.now(); state.duration=Number(track.duration)||p.getDuration()||180; setStatus(state.mixOn?'✅ PLAYING • HOOK 60 วิ':'✅ PLAYING FULL SONG'); els.engineClock.textContent=state.mixOn?'AUTO MIX':'FULL TRACK • AUTO'; startProgressLoop(); prepareNext(); }
function updateNow(){ const t=state.current; if(!t){els.nowTitle.textContent='พร้อมเล่น';els.meta.textContent='—';els.cover.classList.remove('visible');els.coverFallback.style.display='flex';return;} els.nowTitle.textContent=t.title||'Unknown'; els.meta.textContent=t.uploader||'Unknown'; if(t.thumbnail){els.cover.src=t.thumbnail;els.cover.classList.add('visible');els.coverFallback.style.display='none';} }
function prepareNext(){ clearNext(); const idx=state.currentIndex+1; if(idx<state.queue.length){ state.nextIndex=idx; state.next={...state.queue[idx]}; configurePlayer(standbyPlayer(),state.next,0); els.nextLabel.textContent=`เพลงต่อไป: ${state.next.title}\n✅ PRELOAD`; return true; } if(state.autoMusic&&state.current){ els.nextLabel.textContent='เพลงต่อไป: 🔎 AUTO MUSIC กำลังหาเพลงคล้าย…'; autoFindNext(); return false; } els.nextLabel.textContent='เพลงต่อไป: —'; return false; }
function clearNext(){ state.next=null; state.nextIndex=-1; try{standbyPlayer()?.stopVideo()}catch{} }
async function autoFindNext(){ try{ const base=(state.current.uploader||'')+' '+(state.current.title||''); const exclude=[...new Set(state.queue.map(x=>x.id))].join(','); const r=await fetch(`/.netlify/functions/youtube-search?q=${encodeURIComponent(base)}&mode=all&max=8&exclude=${encodeURIComponent(exclude)}`); const rows=await r.json(); if(!r.ok||!Array.isArray(rows)||!rows.length){els.nextLabel.textContent='เพลงต่อไป: หาเพลงอัตโนมัติไม่เจอ';return;} const pick=rows[0]; state.queue.push(pick); uniqueQueue(); save(); renderQueue(); prepareNext(); }catch(e){els.nextLabel.textContent='เพลงต่อไป: AUTO MUSIC มีปัญหา';} }

function startProgressLoop(){ cancelAnimationFrame(state.progressTimer); const loop=()=>{ if(!state.current){return;} const p=currentPlayer(); let pos=0, dur=Number(state.duration)||180; try{pos=Math.max(0,p?.getCurrentTime?.()||0); dur=Math.max(1,p?.getDuration?.()||dur);}catch{} state.duration=dur; const display=state.mixOn?Math.min(CFG.HOOK_SECONDS,pos-hookStart(dur)):pos; const max=state.mixOn?CFG.HOOK_SECONDS:dur; els.progress.max=max; els.progress.value=Math.max(0,Math.min(max,display)); els.timeline.textContent=`${fmt(display)} / ${fmt(max)}`; drawWaveform(display/max,state.current.id); if(!state.paused){ if(state.mixOn && display>=CFG.HOOK_SECONDS-CFG.MIX_SECONDS){ if(state.nextIndex<0 && state.autoMusic) prepareNext(); if(state.next) startCrossfade(); } } state.progressTimer=requestAnimationFrame(loop); }; loop(); }

function startCrossfade(){ if(state.mixTimer||!state.next) return; const incoming=standbyPlayer(), outgoing=currentPlayer(); if(!incoming||!outgoing) return; state.mixTimer={start:performance.now(),outgoing,incoming}; incoming.setVolume(0); incoming.playVideo(); function tick(){ if(!state.mixTimer)return; const p=Math.min(1,(performance.now()-state.mixTimer.start)/(CFG.MIX_SECONDS*1000)); const outV=Math.round(CFG.MAX_VOLUME*Math.cos(Math.PI/2*p)); const inV=Math.round(CFG.MAX_VOLUME*Math.sin(Math.PI/2*p)); try{outgoing.setVolume(outV);incoming.setVolume(inV)}catch{} if(p<1){requestAnimationFrame(tick);return;} try{outgoing.stopVideo();incoming.setVolume(CFG.MAX_VOLUME)}catch{} const oldTitle=state.current; if(oldTitle) recordHistory(oldTitle); state.active=state.active==='A'?'B':'A'; state.currentIndex=state.nextIndex; state.current={...state.next}; state.next=null; state.nextIndex=-1; state.mixTimer=null; state.startedAt=performance.now(); state.duration=Number(state.current.duration)||incoming.getDuration()||180; updateNow(); renderQueue(); setStatus('✅ AUTO MIX • PLAYING'); els.engineClock.textContent='AUTO MIX'; prepareNext(); }
 requestAnimationFrame(tick); }
function transitionOrAdvance(){ if(state.current && state.next) startCrossfade(); else if(state.autoMusic) {prepareNext(); setTimeout(()=>state.next&&startCrossfade(),350);} else setStatus('เพลงจบแล้ว • AUTO MUSIC OFF'); }
function clearMixTimer(){state.mixTimer=null}

function togglePause(){ const p=currentPlayer(); if(!p) return; if(state.paused){p.playVideo();state.paused=false;els.pauseBtn.textContent='⏸ พักเพลง';setStatus('✅ PLAYING');} else {p.pauseVideo();state.paused=true;els.pauseBtn.textContent='▶ เล่นต่อ';setStatus('⏸ PAUSED');} }
function nextManual(){ if(state.currentIndex+1<state.queue.length) startTrack(state.currentIndex+1); else if(state.autoMusic){prepareNext();setTimeout(()=>{if(state.next){state.queue.push(state.next);state.currentIndex=state.queue.length-2;startTrack(state.queue.length-1);}},300);} }
function prevManual(){ if(state.currentIndex>0) startTrack(state.currentIndex-1); }
function stopCurrent(){ try{state.playerA?.stopVideo();state.playerB?.stopVideo();}catch{} state.current=null;state.currentIndex=-1;clearNext();clearMixTimer();cancelAnimationFrame(state.progressTimer);els.progress.value=0;els.timeline.textContent='0:00 / 1:00';updateNow();setStatus('READY');els.engineClock.textContent='AUTO MIX • READY';els.nextLabel.textContent='เพลงต่อไป: —';renderQueue(); }
function seek(f){ const p=currentPlayer(); if(!p||!state.current)return; const dur=Number(state.duration)||180; const target=state.mixOn?hookStart(dur)+f*CFG.HOOK_SECONDS:f*dur; try{p.seekTo(Math.max(0,Math.min(dur,target)),true)}catch{} }

function recordHistory(track){ const item={...track,playedAt:new Date().toLocaleString('th-TH')};state.history=state.history.filter(x=>x.id!==track.id);state.history.unshift(item);state.history=state.history.slice(0,100);save(); }
function showHistory(){ els.historyList.innerHTML=''; if(!state.history.length){els.historyList.innerHTML='<div class="track"><div></div><div>ยังไม่มีประวัติการฟัง</div></div>';} else state.history.forEach((t,i)=>{const el=document.createElement('div');el.className='track';el.innerHTML=`<img class="thumb" src="${escapeAttr(t.thumbnail||'')}" alt=""><div><div class="track-title">${i+1}. ${escapeHtml(t.title)}</div><div class="track-sub">${escapeHtml(t.uploader||'')} • ${escapeHtml(t.playedAt||'—')}</div></div>`;el.ondblclick=()=>{addTrack(t,true);els.historyModal.classList.add('hidden')};els.historyList.appendChild(el)});els.historyModal.classList.remove('hidden');}

function renderWave(){ const c=els.waveform,ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b141d';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1b2936';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(12,h/2);ctx.lineTo(w-12,h/2);ctx.stroke(); const count=Math.max(90,Math.floor(w/4.5)),passed=(state.current?els.progress.value/(Number(els.progress.max)||60):0),t=performance.now()/700;for(let i=0;i<count;i++){const x=12+i*(w-24)/Math.max(1,count-1),frac=i/Math.max(1,count-1);const amp=.18+.8*(.5+.5*Math.sin(frac*34+(state.current?.id||'').length))*(.45+.55*Math.abs(Math.sin(frac*71)));const hh=amp*(h*.38);ctx.fillStyle=frac<=passed?'#b59aff':'#3a4958';ctx.fillRect(x-1.1,h/2-hh,2.2,hh*2);}if(state.current){const x=12+passed*(w-24);ctx.fillStyle='#fff';ctx.fillRect(x-1,7,2,h-14);} }
function drawWaveform(){renderWave()}; window.addEventListener('resize',renderWave); setInterval(renderWave,50); renderWave();

els.searchBtn.onclick=()=>search();els.searchInput.addEventListener('keydown',e=>{if(e.key==='Enter')search()});els.addBtn.onclick=addSelected;els.removeBtn.onclick=removeSelected;els.clearBtn.onclick=clearQueue;els.startBtn.onclick=()=>startTrack(state.selectedQueue<state.queue.length?state.selectedQueue:0);els.pauseBtn.onclick=togglePause;els.nextBtn.onclick=nextManual;els.prevBtn.onclick=prevManual;els.stopBtn.onclick=stopCurrent;els.progress.addEventListener('input',e=>seek(Number(e.target.value)/(Number(e.target.max)||60)));els.mixBtn.onclick=()=>{state.mixOn=!state.mixOn;els.mixBtn.textContent=state.mixOn?'🤖 AUTO MIX • ON':'🤖 AUTO MIX • OFF';els.mixBtn.classList.toggle('active',state.mixOn);els.modeLabel.textContent=state.mixOn?'AUTO • 60 วิ / เพลง | CROSSFADE 4 วิ | PRELOAD':'FULL TRACK | AUTO NEXT | CROSSFADE 4 วิ | PRELOAD';save();if(state.current)prepareNext();};els.autoMusic.checked=state.autoMusic;els.autoMusic.onchange=e=>{state.autoMusic=e.target.checked;save();if(state.current)prepareNext()};els.autoEQ.checked=state.autoEQ;els.autoEQ.onchange=e=>{state.autoEQ=e.target.checked;save()};els.historyBtn.onclick=showHistory;els.closeHistory.onclick=()=>els.historyModal.classList.add('hidden');els.clearHistory.onclick=()=>{state.history=[];save();showHistory()};els.shuffle90Btn.onclick=()=>search('เพลงไทยยุค 1990 2000 GMM Grammy','all',12);els.artistBtn.onclick=()=>{const a=prompt('พิมพ์ชื่อศิลปิน');if(a)search(a,'official',12)};['bass','music','vocal'].forEach(k=>{const s=$(k),o=$(k+'Value');s.oninput=()=>o.textContent=`${Number(s.value)>0?'+':''}${s.value} dB`});

function escapeAttr2(s){return String(s||'').replace(/"/g,'&quot;')}
uniqueQueue();renderQueue();els.mixBtn.textContent=state.mixOn?'🤖 AUTO MIX • ON':'🤖 AUTO MIX • OFF';els.mixBtn.classList.toggle('active',state.mixOn);els.autoMusic.checked=state.autoMusic;els.autoEQ.checked=state.autoEQ;
